# Generated by Django 4.1.5 on 2023-03-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerador',
            name='liberado',
            field=models.IntegerField(default=0),
        ),
    ]
