# Generated by Django 4.1.5 on 2023-03-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorios', '0002_gerador_liberado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerador_celesc',
            name='liberado',
            field=models.IntegerField(default=0),
        ),
    ]
