# Generated by Django 4.1.5 on 2023-06-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorios', '0003_gerador_celesc_liberado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerador',
            name='Imposto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gerador_celesc',
            name='Imposto',
            field=models.IntegerField(default=0),
        ),
    ]
