# Generated by Django 4.1.5 on 2023-06-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorios', '0005_gerador_descontocliente_gerador_descontogestao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerador',
            name='descontoCliente',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gerador',
            name='descontoGestao',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gerador_celesc',
            name='descontoCliente',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gerador_celesc',
            name='descontoGestao',
            field=models.IntegerField(default=0),
        ),
    ]
