# Generated by Django 4.1.5 on 2023-06-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorios', '0006_alter_gerador_descontocliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerador',
            name='Imposto',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='gerador_celesc',
            name='Imposto',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
