# Generated by Django 4.1.5 on 2023-06-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relatorios', '0007_alter_gerador_imposto_alter_gerador_celesc_imposto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerador',
            name='Imposto',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='gerador_celesc',
            name='Imposto',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
