# Generated by Django 4.2.2 on 2023-06-18 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_remove_clientes_distribuidora'),
        ('Distribuidoras', '0002_distribuidoras_cliente'),
        ('Administradores', '0003_administradores_uc'),
        ('Relatorios', '0008_alter_gerador_imposto_alter_gerador_celesc_imposto'),
    ]

    operations = [
        migrations.CreateModel(
            name='historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uc', models.CharField(max_length=50)),
                ('Referencia', models.CharField(max_length=50)),
                ('ValorBruto', models.CharField(max_length=50)),
                ('splitConsumo', models.CharField(max_length=50)),
                ('faturaGerador', models.CharField(max_length=50)),
                ('descontoCliente', models.CharField(max_length=50)),
                ('splitCliente', models.CharField(max_length=50)),
                ('descontoGerador', models.CharField(max_length=50)),
                ('splitGerador', models.CharField(max_length=50)),
                ('descontoImpostos', models.CharField(max_length=50)),
                ('splitBruto', models.CharField(max_length=50)),
                ('splitFatura', models.CharField(max_length=50)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Administradores.administradores')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.clientes')),
                ('distribuidora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Distribuidoras.distribuidoras')),
            ],
        ),
    ]
