# Generated by Django 4.1.5 on 2023-02-23 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_remove_clientes_distribuidora'),
        ('Distribuidoras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuidoras',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.clientes'),
        ),
    ]
