# Generated by Django 4.1.5 on 2023-01-07 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Distribuidoras', '0001_initial'),
        ('Geradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geradores',
            name='distribuidora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Distribuidoras.distribuidoras'),
        ),
    ]
