# Generated by Django 4.1.5 on 2023-01-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geradores', '0003_geradores_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='geradores',
            name='descontoCliente',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='geradores',
            name='descontoGestao',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
