# Generated by Django 4.1.5 on 2023-02-04 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_clientes_status'),
        ('Geradores', '0004_geradores_descontocliente_geradores_descontogestao'),
    ]

    operations = [
        migrations.AddField(
            model_name='geradores',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.clientes'),
        ),
    ]
