# Generated by Django 4.1.5 on 2023-03-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geradores', '0005_geradores_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='geradores',
            name='senha',
            field=models.CharField(default=1234, max_length=30),
            preserve_default=False,
        ),
    ]
