# Generated by Django 4.1.5 on 2023-06-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Geradores', '0007_alter_geradores_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geradores',
            name='descontoCliente',
        ),
        migrations.RemoveField(
            model_name='geradores',
            name='descontoGestao',
        ),
    ]
