# Generated by Django 4.1.5 on 2023-03-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administradores', '0002_administradores_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='uc',
            field=models.CharField(default=84683481000177, max_length=50),
            preserve_default=False,
        ),
    ]
