# Generated by Django 4.1.5 on 2023-02-03 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Distribuidoras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=250)),
                ('fone', models.CharField(max_length=15)),
                ('distribuidora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Distribuidoras.distribuidoras')),
            ],
        ),
    ]
