# Generated by Django 4.1.5 on 2023-02-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
