# Generated by Django 4.1.5 on 2023-02-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_clientes_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='distribuidora',
        ),
    ]
