# Generated by Django 4.1.5 on 2023-02-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Distribuidoras', '0001_initial'),
        ('Clientes', '0002_clientes_status'),
        ('Administradores', '0001_initial'),
        ('Geradores', '0005_geradores_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('uc', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Administradores.administradores')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clientes.clientes')),
                ('distribuidora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Distribuidoras.distribuidoras')),
                ('gerador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Geradores.geradores')),
            ],
        ),
    ]
